version: '3'

services:
  laravel:
    build:
      context: .
      dockerfile: ./laravel/Dockerfile.prod
    image: murilohenzo/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    image: murilohenzo/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"

networks:
  laranet:
    driver: bridge